### ISSUE TITLE
 This lab seems like it might be missing something called 'twisted'

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/python-variables-lab#1]
Tests fail when running them with this message:

<img width="1426" alt="screen shot 2018-04-01 at 1 46 01 pm" src="https://user-images.githubusercontent.com/13033515/38175955-683ac15a-35b3-11e8-9cbe-9f9374a12898.png">

You can take a look at the test return by opening up the redux tools and taking a look at the jupyter key in state.

@JeffKatzy

**Comment by tkoar** [comment]
There was an import for twisted.trial from unittest. I removed the import and updated the tests -- which I've tested in the browser.
