### ISSUE TITLE
Unable to run tests locally

### ISSUE THREAD

**Issue by nigelfloe** [learn-co-curriculum/python-variables-lab#2]
When I click the 'Run Tests' button. Nothing seems to happen. I'm pretty sure my answers are right, unless I'm missing something in my understanding of what the expected output of each cell should be. Even if the tests are failing, I'm not getting any actionable information. I simply click the button and nothing changes:
http://recordit.co/AOmw0Hdxsg

Looking at the console, I see a number of warnings (some are debug logs), and a `net::ERR_ABORTED` error from a GET request to https://nyc-04-47821.ide-proxy.ide.learn.co/nbextensions/widgets/notebook/js/extension.js?v=20180403001515. See screenshot:
<img width="1664" alt="screen shot 2018-04-02 at 8 17 42 pm" src="https://user-images.githubusercontent.com/13008589/38222516-288c7dae-36b3-11e8-9777-2294a1a54f99.png">

One of the warnings reads `Please install widgetsnbextension or ipywidgets 4.0`. I tried to install ipywidgets in the notebook (`!pip install ipywidgets`), but it did not seem to change the behavior.

I'm running macOS 10.13.3 in Chrome V64.0.3282.186

**Comment by tkoar** [comment]
The test file has been updated, which should solve this issue. please refer to #1

**Comment by nigelfloe** [comment]
@tkoar thanks for the update, but I am seeing no change in the behavior I've reported

**Comment by nigelfloe** [comment]
resolved by deleting my fork, and reloading the lab. thanks again :)
