### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/python-variables-lab#3]
Shouldn't the solutions file  contain "=" instead of "#" to comment everything out?

ex. below

travel_month = "January"
Now let's assign a variable equal to the number of weeks that you would like to travel, 3.

number_of_weeks = None
number_of_weeks = 3
Now, you just learned that you can travel for a longer period of time. So reassign the number_of_weeks variable equal to 5.

number_of_weeks = 5
Now that's more like it.

**Comment by LoreDirick** [comment]
You're right, solutions weren't there.
Thanks for raising this issue @GeoffWT ! It's fixed now.
